#include "extern_vars.h"

uint8_t IR_INT_STATE=NOT_FLAGGED;
uint8_t PI_INT_STATE=NOT_FLAGGED;
uint8_t CLAW_INT_STATE=NOT_FLAGGED;
uint8_t EDGE_LEFT_STATE=NOT_FLAGGED;
uint8_t EDGE_RIGHT_STATE=NOT_FLAGGED;
uint8_t TAPE_LEFT_STATE=NOT_FLAGGED;
uint8_t TAPE_RIGHT_STATE=NOT_FLAGGED;
